# Catalog for API Workbench.
# PFX: C:\pult-certs\*.pfx (Docker → /certs)

splunk_url: 'https://splunk.company.com/en-US/app/KESCloud/search?earliest=-15m&latest=now&q=search%20index%3D"*"%20%7C%20search%20ConversationId%3D"#ConversationId#"&display.page.search.mode=smart&dispatch.sample_ratio=1'

services:
  # One root: UserPortal = token+cert, backend = cert only
  - name: order-service
    description: Управление заказами
    color: "#4CAF50"
    proxy: true
    swagger:
      - name: UserPortal
        url: http://localhost:5157/userportal/swagger.yml
        auth: basic
        username: u1
        password: "123"
        environments:
          dev: http://localhost:5157/userportal
          stage: https://api.stage.company.com/userportal
          prod: https://api.prod.company.com/userportal
        api_auth:
          type: token
          token_url:
            dev: https://auth.dev.company.com/token
            stage: https://auth.stage.company.com/token
            prod: https://auth.prod.company.com/token
          cert_path: client.pfx
      - name: backend
        url: https://host/swagger/backend/swagger.json
        auth: basic
        username: u1
        password: "123"
        environments:
          dev: https://api.dev.company.com/order
          stage: https://api.stage.company.com/order
          prod: https://api.prod.company.com/order
        api_auth:
          type: certificate
          cert_path: client.pfx
    environments:
      dev: http://localhost:5157/userportal
      stage: https://api.stage.company.com/userportal
      prod: https://api.prod.company.com/userportal
    auth:
      type: none
